uploads = []
generated = []

[[outputs]]
id = "vTzmKfX1cjZiSI23Lgq0c"
uri = "file://exports/crypto-trader-project.tar.gz"
type = "unspecified"
title = "전체 프로젝트 (crypto-trader-project.tar.gz)"

[[outputs]]
id = "WCpNgVcxAuq0ZmUqRRoyX"
uri = "file://exports/ai-trading-code.tar.gz"
type = "unspecified"
title = "AI 매매 전체 코드 (ai-trading-code.tar.gz)"
